### ISSUE TITLE
System.Text.Encoding.Web Vulnerability

### ISSUE THREAD

**Issue by blakes3489** [RockLib/RockLib.HealthChecks#16]
There is a vulnerability identified by snyk: https://app.snyk.io/vuln/SNYK-DOTNET-SYSTEMTEXTENCODINGSWEB-1253267 that can be addressed with a simple version update.

**Comment by bfriesen** [comment]
I'm confused, we don't take a dependency on System.Text.Encodings.Web. Where is the vulnerability here?

**Comment by blakes3489** [comment]
Detailed paths
Introduced through: project@* › RockLib.Configuration@2.5.2 › Microsoft.Extensions.Configuration.Json@5.0.0 › System.Text.Json@5.0.0 › System.Text.Encodings.Web@5.0.0
Introduced through: project@* › RockLib.HealthChecks.AspNetCore@2.0.6 › RockLib.HealthChecks@1.3.8 › RockLib.Configuration@2.5.2 › Microsoft.Extensions.Configuration.Json@5.0.0 › System.Text.Json@5.0.0 › System.Text.Encodings.Web@5.0.0

**Comment by bfriesen** [comment]
Ok, so when we fix this in RockLib.Configuration, we'll need to propagate to satellite libraries like this one. We'll make sure to take care of that after fixing RockLib.Configuration.
